id: I0118E7E1
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T23:15:31+00:00'
last_modified: '2022-06-08T13:17:24.508221+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG15233
  title: བཀའ་འགྱུར་གྱི་དཀར་ཆག ༼དབུ་ཅན་བྲིས་མ།༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '3727':
      image_group_id: I1KG15252
      title: ''
      total_pages: 228
      order: 1
      base_file: 3727.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
